blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('index/', views.index, name='index'),
    path("add/", views.add, name='add'),
    path('add/action', views.add_action, name='add_action'),
    path('article/<int:article_id>', views.article, name='article'),
    path('edit/<int:article_id>', views.edit, name='edit')

]

blog2/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('index/', views.index),
]

djangoWeb/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('blog2/', include('blog2.urls')),
]

blog/models.py
from django.db import models


class Article(models.Model):

    # 每次修改都必须执行下面命令
    # python manage.py makemigrations
    # python manage.py migrate
    title = models.CharField(max_length=255, default='title')
    name = models.TextField(null=True)
    content = models.TextField(null=True)
    pub_time = models.DateTimeField(null=True)

    # 在admin管理界面中，显示标题信息
    def __str__(self):
        return self.title

blog2/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import models

def index(request):

    aritcles = models.Article.objects.all()
    return render(request, 'blog/index.html',{'aritcles': aritcles})

def add(request):
    return render(request, 'blog/article.html')

def add_action(request):
    title = request.POST['title']
    content = request.POST['content']
    article_id = request.POST['article_id']
    if article_id == '0':
        #新增
        models.Article.objects.create(title=title, name=content)
        aritcles = models.Article.objects.all()
        return render(request, 'blog/index.html', {'aritcles': aritcles})
    #编辑
    article = models.Article.objects.get(pk=article_id)
    article.title = title
    article.name = content
    article.save()
    return render(request, 'blog/article_detail.html', {'aritcle': article})

def article(request, article_id):
    aritcle = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/article_detail.html',{'aritcle': aritcle})

def edit(request, article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/article.html', {'article':article})

blog2/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'blog2/index.html',
                  {'name': 'xiaoqiu2222', 'age': 18})

blog/templates/blog/article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>article</title>
</head>
<style>
    body{
           margin-left: 40%;
    }
</style>
<body>
    <form action="{% url 'blog:add_action' %}" method="post">
        {% csrf_token %}
            <!-- 过滤器 default 默认值 -->
            <input hidden name="article_id" value="{{ article.id | default:'0'}}">
            <b>标题</b> ： <input type="text" name='title' value="{{ article.title }}"/> <br/>
            <b>内容</b> ： <input type="text" name='content' value="{{ article.name }}" /><br/><br/>
        <input type="submit" value="提交">
     </form>
</body>
</html>

blog/templates/blog/article_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>article_detail</title>
</head>
<style>
    body{
        margin-left: 40%;
    }
</style>
<body>
    <h>{{ aritcle.title }}</h>
    <br>
    <p>{{ aritcle.name }}</p>
    <br>
    <a href="{% url 'blog:index' %}">返回首页</a>
    <br>
    <a href="{% url 'blog:edit' aritcle.id %}">编辑</a>
</body>
</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<style>
    body{
           margin-left: 40%;
    }
</style>
<body>
<a href="{% url 'blog:add'%}" >新文章</a><br/><br/>
{% for aritcle in aritcles %}
    <a href="{% url 'blog:article' aritcle.id %}">{{aritcle.title}}</a><br/>
{% endfor %}
<br/>

</body>
</html>

blog2/templates/blog2/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>这里是测试python的blog2</h1>
<p>{{ name }}</p>
</body>
</html>